//! Generate a hardened Dockerfile from a `BuildSpec`.
//!
//! Pure function with no IO; the generator is responsible only for emitting
//! the Dockerfile string. Build context staging is the orchestrator's job.

use indoc::formatdoc;

use crate::domain::{BaseImage, BuildSpec, HardeningOptions, Runtime};

const NON_ROOT_UID: u32 = 1000;
const NON_ROOT_GID: u32 = 1000;

pub fn render(spec: &BuildSpec) -> String {
    let base_ref = base_reference(spec.runtime, spec.base_image);
    let workdir = "/app";
    let entry = entrypoint(spec.runtime);
    let stripping = stripping_layer(spec.base_image, &spec.hardening);
    let user_create = user_create_section(spec.base_image, &spec.hardening);
    let user_switch = user_switch_section(spec.base_image, &spec.hardening);
    let labels = labels(spec);

    formatdoc! {r#"
        # syntax=docker/dockerfile:1.7
        # Generated by SecureImage Forge — DO NOT edit by hand.
        FROM {base_ref}

        WORKDIR {workdir}

        {labels}

        COPY . {workdir}

        {user_create}

        {stripping}

        {user_switch}

        ENTRYPOINT {entry}
    "#}
}

pub(crate) fn base_reference(runtime: Runtime, base: BaseImage) -> &'static str {
    match (runtime, base) {
        (Runtime::Java, BaseImage::Alpine) => "eclipse-temurin:21-jre-alpine",
        (Runtime::Java, BaseImage::Debian) => "eclipse-temurin:21-jre-jammy",
        (Runtime::Java, BaseImage::Distroless) => "gcr.io/distroless/java21-debian12:nonroot",
        (Runtime::Dotnet, BaseImage::Alpine) => "mcr.microsoft.com/dotnet/runtime:8.0-alpine",
        (Runtime::Dotnet, BaseImage::Debian) => "mcr.microsoft.com/dotnet/runtime:8.0-jammy",
        (Runtime::Dotnet, BaseImage::Distroless) => {
            "mcr.microsoft.com/dotnet/runtime-deps:8.0-distroless"
        }
        (Runtime::Go, BaseImage::Alpine) => "alpine:3.20",
        (Runtime::Go, BaseImage::Debian) => "debian:12-slim",
        (Runtime::Go, BaseImage::Distroless) => "gcr.io/distroless/static-debian12:nonroot",
        (Runtime::Node, BaseImage::Alpine) => "node:22-alpine",
        (Runtime::Node, BaseImage::Debian) => "node:22-bookworm-slim",
        (Runtime::Node, BaseImage::Distroless) => "gcr.io/distroless/nodejs22-debian12:nonroot",
        (Runtime::Python, BaseImage::Alpine) => "python:3.13-alpine",
        (Runtime::Python, BaseImage::Debian) => "python:3.13-slim-bookworm",
        (Runtime::Python, BaseImage::Distroless) => "gcr.io/distroless/python3-debian12:nonroot",
    }
}

fn entrypoint(runtime: Runtime) -> &'static str {
    match runtime {
        Runtime::Java => r#"["java","-jar","/app/app.jar"]"#,
        Runtime::Dotnet => r#"["dotnet","/app/app.dll"]"#,
        Runtime::Go => r#"["/app/app"]"#,
        Runtime::Node => r#"["node","/app/index.js"]"#,
        Runtime::Python => r#"["python","/app/main.py"]"#,
    }
}

fn stripping_layer(base: BaseImage, h: &HardeningOptions) -> String {
    if matches!(base, BaseImage::Distroless) {
        return "# Distroless base — no shell or package manager present.".to_string();
    }
    if !h.remove_shells && !h.remove_pkg_managers {
        return "# Hardening: strip skipped.".to_string();
    }
    let mut steps: Vec<String> = Vec::new();
    if h.remove_pkg_managers {
        match base {
            BaseImage::Alpine => {
                steps.push("apk del --no-cache apk-tools 2>/dev/null || true".into())
            }
            BaseImage::Debian => steps.push(
                "apt-get purge -y --auto-remove apt apt-utils dpkg && rm -rf /var/lib/apt/lists/*"
                    .into(),
            ),
            BaseImage::Distroless => {}
        }
    }
    if h.remove_shells {
        steps.push("rm -f /bin/sh /bin/bash /bin/dash /bin/ash || true".into());
    }
    let joined = steps.join(" && ");
    format!("RUN {joined}")
}

fn user_create_section(base: BaseImage, h: &HardeningOptions) -> String {
    if !h.non_root_user {
        return "# Hardening: user creation skipped (non-root user disabled).".to_string();
    }
    if matches!(base, BaseImage::Distroless) {
        return "# Distroless base has built-in nonroot user.".to_string();
    }
    let create = match base {
        BaseImage::Alpine => format!(
            "addgroup -S -g {NON_ROOT_GID} app && adduser -S -D -H -u {NON_ROOT_UID} -G app app"
        ),
        BaseImage::Debian => format!(
            "groupadd -g {NON_ROOT_GID} app && useradd -m -u {NON_ROOT_UID} -g app -s /sbin/nologin app"
        ),
        BaseImage::Distroless => unreachable!(),
    };
    format!("RUN {create}")
}

fn user_switch_section(base: BaseImage, h: &HardeningOptions) -> String {
    if !h.non_root_user {
        return "# Hardening: non-root user disabled.".to_string();
    }
    if matches!(base, BaseImage::Distroless) {
        return "USER nonroot".to_string();
    }
    format!("USER {NON_ROOT_UID}:{NON_ROOT_GID}")
}

fn labels(spec: &BuildSpec) -> String {
    let runtime = format!("{:?}", spec.runtime).to_lowercase();
    let base = format!("{:?}", spec.base_image).to_lowercase();
    let compliance = spec
        .compliance
        .iter()
        .map(|c| format!("{c:?}").to_lowercase())
        .collect::<Vec<_>>()
        .join(",");
    formatdoc! {r#"
        LABEL org.opencontainers.image.title="{name}" \
              org.opencontainers.image.vendor="SecureImage Forge" \
              forge.runtime="{runtime}" \
              forge.base="{base}" \
              forge.compliance="{compliance}"
    "#, name = spec.name}
    .trim_end()
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{Architecture, BuildSpec, ComplianceProfile, HardeningOptions, Runtime};
    use std::collections::BTreeSet;

    fn spec(rt: Runtime, base: BaseImage) -> BuildSpec {
        let mut archs = BTreeSet::new();
        archs.insert(Architecture::Amd64);
        let mut compliance = BTreeSet::new();
        compliance.insert(ComplianceProfile::Cis);
        BuildSpec {
            name: "test-app".into(),
            runtime: rt,
            base_image: base,
            architectures: archs,
            compliance,
            hardening: HardeningOptions::strict(),
            generate_sbom: true,
            sign: true,
        }
    }

    #[test]
    fn alpine_java_strict_includes_user_and_strip() {
        let df = render(&spec(Runtime::Java, BaseImage::Alpine));
        assert!(df.contains("eclipse-temurin"));
        assert!(df.contains("addgroup"));
        assert!(df.contains("USER 1000:1000"));
        assert!(df.contains("rm -f /bin/sh"));
        assert!(df.contains("forge.compliance=\"cis\""));
    }

    #[test]
    fn distroless_skips_strip_uses_nonroot() {
        let df = render(&spec(Runtime::Java, BaseImage::Distroless));
        assert!(df.contains("distroless/java21"));
        assert!(df.contains("USER nonroot"));
        assert!(!df.contains("apk del"));
        assert!(!df.contains("apt-get purge"));
    }

    #[test]
    fn debian_python_strict_uses_apt_purge() {
        let df = render(&spec(Runtime::Python, BaseImage::Debian));
        assert!(df.contains("python:3.13-slim-bookworm"));
        assert!(df.contains("apt-get purge"));
        assert!(df.contains("useradd"));
    }

    #[test]
    fn no_hardening_emits_skip_comments() {
        let mut s = spec(Runtime::Go, BaseImage::Alpine);
        s.hardening = HardeningOptions {
            remove_shells: false,
            remove_pkg_managers: false,
            readonly_rootfs: false,
            non_root_user: false,
        };
        let df = render(&s);
        assert!(df.contains("strip skipped"));
        assert!(df.contains("non-root user disabled"));
    }
}
