apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reference-service
  annotations:
    github.com/project-slug: acme/reference-service
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "service=reference-service"
spec:
  type: service
  lifecycle: production
  owner: group:platform-engineering
  system: platform
